stages:
  - prepare
  - compile
  - release
  - publish

prepare makefile:
  stage: prepare
  artifacts:
    expire_in: 1 day
    paths:
    - Makefile.properties
    - .version
  script:
  - echo "BINARY_FILENAME=${BINARY_FILENAME}" > Makefile.properties
  - echo "DOCKER_REGISTRY_HOSTNAME=${DOCKER_REGISTRY_HOSTNAME}" >> Makefile.properties
  - echo "DOCKER_IMAGE_NAMESPACE=${DOCKER_IMAGE_NAMESPACE}" >> Makefile.properties
  - echo "DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME}" >> Makefile.properties
  - echo "GITHUB_REPOSITORY_URL=${GITHUB_REPOSITORY_URL}" >> Makefile.properties
  - make version.next > .version

compile:
  stage: compile
  services: ['docker:dind']
  dependencies: ['prepare makefile']
  artifacts:
    expire_in: 3 days
    paths:
    - bin
  script:
  - make compile

github:
  stage: release
  services: ['docker:dind']
  dependencies: ['prepare makefile']
  script:
  - if [ "${GITHUB_REPOSITORY_URL}" != "" ]; then make release.github fi;

dockerhub:
  stage: release
  services: ['docker:dind']
  dependencies: ['prepare makefile']
  script:
  - |
    if [ "${DOCKER_REGISTRY_USERNAME}" != "" ] && [ "${DOCKER_REGISTRY_PASSWORD}" != "" ]; then
      docker login ${DOCKER_REGISTRY_HOSTNAME} -u ${DOCKER_REGISTRY_USERNAME} -p ${DOCKER_REGISTRY_PASSWORD};
      make release.dockerhub;
      docker logout;
    fi;
